{
 "title": "JPWS",
 "description": "Dashboard for official Prometheus Python Client's metrics",
 "tags": [
  "flask",
  "app",
  "web",
  "python"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "percentile", "label": "Percentile", "query": "100,99,95,90,75,50,25" }
  ]
 },
 "panels": [
  {
   "title": "Latency within which $percentile% of requests served",
   "type": "graph",
   "description": "See more:\nhttps://prometheus.io/docs/practices/histograms/",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($percentile / 100, sum(rate(flask_http_request_duration_seconds_bucket[$interval])) by (le))",
     "legendFormat": "latency"
    }
   ]
  },
  {
   "title": "4xx, 5xx errors count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flask_http_request_total{status=~\"4..|5..\"}",
     "legendFormat": "{{ status }}"
    },
    {}
   ]
  },
  {
   "title": "4xx, 5xx errors per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_total{status=~\"4..|5..\"}[$interval]))",
     "legendFormat": " Errors per second"
    },
    {}
   ]
  },
  {
   "title": "JPWS Logging",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{task=\"jpws\"}"
    }
   ]
  },
  {
   "title": "Request Latency, s",
   "type": "graph",
   "description": "Latency",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_sum[$interval]) \n/ \nrate(flask_http_request_duration_seconds_count[$interval])",
     "legendFormat": "{{ method }} {{ pod }}{{ exported_endpoint }}"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "graph",
   "description": "Requests per second ",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(flask_http_request_total[$interval])",
     "legendFormat": "{{method}} - {{status}}"
    }
   ]
  }
 ]
}