name: Docker Image CI

on:
  [workflow_dispatch]
 
jobs:

  build:
    name: "Docker Build"
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      working-directory: ./vagrant/jpws/python
      run: docker build . --file Dockerfile --tag jpws:${{github.run_number}}
      
  apply:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    environment: "Dev"

    steps:
    - name: Run Terraform Apply
      run: echo "Run terraform apply"
    
